repos:
  - repo: local
    hooks:
      - id: doctoc
        name: doctoc README
        entry: bash -c 'npx doctoc "$@" --github --notitle && git add -u "**/README.md"' --
        language: system
        files: README\.md$
        pass_filenames: true
        stages: [pre-commit]

      - id: fmt-check
        name: just fmt-check
        entry: scripts/run-check fmt-check
        language: system
        types: [rust]
        pass_filenames: true
        stages: [pre-commit, pre-push]

      - id: lint
        name: just lint
        entry: scripts/run-check lint
        language: system
        types: [rust]
        pass_filenames: true
        stages: [pre-push]

      - id: test
        name: just test
        entry: scripts/run-check test
        language: system
        types: [rust]
        pass_filenames: true
        stages: [pre-push]

      - id: doc-check
        name: just doc-check
        entry: scripts/run-check doc-check
        language: system
        types: [rust]
        pass_filenames: true
        stages: [pre-push]
