tag-name = "{{crate_name}}-v{{version}}"
dependent-version = "upgrade"
pre-release-hook = ["sh", "-c", "git cliff -o $CRATE_ROOT/CHANGELOG.md --include-path \"$CRATE_ROOT/**\" --tag {{crate_name}}-v{{version}} && git add $CRATE_ROOT/CHANGELOG.md"]
consolidate-commits = true
pre-release-commit-message = "chore(release): bump crate versions"
