shared-version = true
tag-name = "v{{version}}"
dependent-version = "upgrade"
pre-release-hook = ["sh", "-c", "git cliff -o $CRATE_ROOT/CHANGELOG.md --include-path \"$CRATE_ROOT/**\" --tag v{{version}} && git add $CRATE_ROOT/CHANGELOG.md"]
pre-release-commit-message = "release: v{{version}}"
