[application]

[web.app]

# Tailwind CSS configuration
tailwind_input = "tailwind.css"
tailwind_output = "assets/tailwind.css"

# HTML title tag content
title = "aether-desktop"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
