#![doc = include_str!("../docs/components_module.md")]

pub mod app;
pub mod command_picker;
pub(crate) mod common;
pub(crate) mod context_bar;
pub(crate) mod conversation_screen;
pub mod conversation_window;
pub(crate) mod dropped_files;
pub mod elicitation_form;
pub mod file_list_panel;
pub mod file_picker;
pub mod file_tree;
pub mod git_diff;
pub mod input_prompt;
pub mod model_selector;
pub mod plan_review;
pub(crate) mod plan_tracker;
pub mod plan_view;
pub mod progress_indicator;
pub(crate) mod prompt_composer;
pub mod provider_login;
pub(crate) mod reasoning_bar;
pub(crate) mod review_comments;
pub mod server_status;
pub(crate) mod session_picker;
pub mod status_line;
pub(crate) mod sub_agent_tracker;
pub mod text_input;
pub mod thought_message;
pub mod tool_call_status_view;
pub mod tool_call_statuses;
pub(crate) mod tracked_tool_call;

pub use tui::wrap_selection;
